name: Destroy ECS Infrastructure

on:
  workflow_dispatch:  # déclenchement manuel dans GitHub Actions.

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: dev

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: terraform
        run: terraform init -input=false 

      - name: Terraform Destroy
        working-directory: terraform
        run: terraform destroy -auto-approve -var="image_tag=${IMAGE_TAG}"
